on:
  pull_request_target:
    types: [opened, synchronize, ready_for_review, labeled, unlabeled]
  workflow_run:
    workflows: [pr_review.yml]
    types:
      - completed
  issue_comment:
    types: [created]
  push:
    branches:
      - 'main'
  issues:
    types: [labeled, unlabeled]
        
permissions:
  contents: read
  issues: write
  pull-requests: write
  discussions: write
 
name: Testing
jobs:
  check_comments:
    name: Check comments for /assign
    runs-on: ubuntu-latest
    steps:
      - uses: ForgeForce/ForgeCommands@jvm
        with:
          gh_app_key: ${{ secrets.GH_APP_KEY2 }}
          gh_app_name: ${{ secrets.GH_APP_NAME }}
          config_directory: ForgeForce/ActionsStore:configs@main
