on: issue_comment
        
permissions:
  contents: read
  issues: write
  pull-requests: write
  discussions: write
 
name: Testing
jobs:
  check_comments:
    name: Check comments for /assign
    runs-on: ubuntu-latest
    steps:
      - uses: ForgeForce/ForgeCommands@63903a083c0c308a588bc9f484315f6aff56c884
        with:
          who-to-greet: 'sup'
