on:
  pull_request:
    types: [opened, synchronize, ready_for_review]
  pull_request_review:
    types: [submitted]
  issue_comment:
    types: [created]
  push:
    branches:
      - 'main'
        
permissions:
  contents: read
  issues: write
  pull-requests: write
  discussions: write
 
name: Testing
jobs:
  check_comments:
    name: Check comments for /assign
    runs-on: ubuntu-latest
    steps:
      - uses: ForgeForce/ForgeCommands@jvm
        with:
          gh_app_key: ${{ secrets.GH_APP_KEY2 }}
          gh_app_name: ${{ secrets.GH_APP_NAME }}
          triage_team: test-team
          triage_project: 4
          labels_to_teams: default -> test-team, rendering -> rendering-people
          latest_version: 1.19
