on: issue_comment
        
permissions:
  contents: read
  issues: write
  pull-requests: write
  discussions: write
 
name: Testing
jobs:
  check_comments:
    name: Check comments for /assign
    runs-on: ubuntu-latest
    steps:
      - uses: ForgeForce/ForgeCommands@05914f79928df33c90726aa59ceb63b9015cbb47
        with:
          who-to-greet: 'sup'
