on: issue_comment
        
permissions:
  contents: read
  issues: write
  pull-requests: write
  discussions: write
 
name: Testing
jobs:
  check_comments:
    name: Check comments for /assign
    runs-on: ubuntu-latest
    steps:
      - uses: ForgeForce/ForgeCommands@32e0651250bd6e048d9e38548b282797f49b7379
        with:
          who-to-greet: 'sup'
