on: issue_comment
        
permissions:
  contents: read
  issues: write
  pull-requests: write
  discussions: write
 
name: Testing
jobs:
  check_comments:
    name: Check comments for /assign
    runs-on: ubuntu-latest
    steps:
      - uses: ForgeForce/ForgeCommands@a31ba99341b96ff4f17bede8695979878e8a6d28
        with:
          who-to-greet: 'sup'
