name: Test Webhooks

on: workflow_dispatch

jobs:

  publish:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout project sources

      uses: actions/checkout@v2

    - uses: matyrobbrt/action-webhooks@main
      with:
        webhook_url: ${{ secrets.WEBHOOK_URL }}
        status: 'started'
        version: '1.0.0'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
